# Generated by Django 2.2.5 on 2019-09-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terreno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombrebanco', models.CharField(help_text='Ingrese su Nombre Banco', max_length=50, null=True, verbose_name='Nombre Banco')),
                ('siglabanco', models.CharField(blank=True, help_text='Ingrese la Sigla Banco', max_length=15, null=True, verbose_name='Sigla Banco')),
            ],
            options={
                'verbose_name_plural': 'Bancos',
                'ordering': ['-creacion'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('emailcliente', models.CharField(blank=True, help_text='Ingrese Email', max_length=50, null=True, verbose_name='Correo Electronico')),
                ('residenciacliente', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['creacion'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('numerocuenta', models.CharField(help_text='Ingrese Numero de Cuenta Banco', max_length=60, unique=True, verbose_name='Numero de Cuenta Banco')),
                ('banco', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contrato.Banco')),
            ],
            options={
                'verbose_name_plural': 'Cuenta',
                'ordering': ['-creacion'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombregrupo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripciongrupo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombremoneda', models.CharField(blank=True, help_text='Ingrese el Nombre de la Moneda', max_length=20, null=True, verbose_name='Moneda')),
                ('siglamoneda', models.CharField(blank=True, help_text='Ingrese la Sigla de la Moneda', max_length=20, null=True, verbose_name='Sigla de la Moneda')),
                ('detallemoneda', models.TextField(blank=True, help_text='Ingrese el Detalle de la Moneda', null=True, verbose_name='Detalle de la Moneda')),
            ],
            options={
                'verbose_name_plural': 'Monedas',
                'ordering': ['-creacion'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombrepersona', models.CharField(blank=True, help_text='Ingrese su Nombre', max_length=100, null=True, verbose_name='Nombre')),
                ('paternopersona', models.CharField(blank=True, help_text='Ingrese su Apellido Paterno', max_length=100, null=True, verbose_name='Apellido Paterno')),
                ('maternopersona', models.CharField(blank=True, help_text='Ingrese su Apellido Materno', max_length=100, null=True, verbose_name='Apellido Materno')),
                ('cipersona', models.CharField(help_text='Ingrese su Numero de Cedula de Identidad', max_length=20, null=True, unique=True, verbose_name='Cedula de Identidad')),
                ('expedidopersona', models.CharField(choices=[('', 'Desconocido'), ('Pando', 'Pando'), ('Beni', 'Beni'), ('La Paz', 'La Paz'), ('Cochabamba', 'Cochabamba'), ('Oruro', 'Oruro'), ('Santa Cruz', 'Santa Cruz'), ('Potosi', 'Potosi'), ('Tarija', 'Tarija'), ('Chuquisaca', 'Chuquisaca')], help_text='Ingrese Expedido Ci', max_length=20, verbose_name='Expedido')),
                ('nacimientopersona', models.DateField(blank=True, help_text='Seleccione su fecha de nacimiento', null=True, verbose_name='Fecha de nacimiento')),
                ('generopersona', models.BooleanField(choices=[(True, 'Hombre'), (False, 'Mujer')], default=1, help_text='Ingrese Genero', verbose_name='Genero')),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'ordering': ['creacion'],
            },
        ),
        migrations.CreateModel(
            name='Urbanizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombreubanizacion', models.CharField(blank=True, help_text='Ingrese del Nombre Ubanizacion', max_length=50, null=True, verbose_name='Nombre Ubanizacion')),
                ('logoubanizacion', models.ImageField(blank=True, null=True, upload_to='static/photos/')),
                ('cuentas', models.ManyToManyField(blank=True, to='contrato.Cuenta')),
                ('ubicacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terreno.Ubicacion')),
            ],
            options={
                'verbose_name_plural': 'Urbanizacion',
                'ordering': ['creacion'],
            },
        ),
        migrations.CreateModel(
            name='Referenciacelular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('numeroreferenciacelular', models.CharField(blank=True, help_text='Ingrese Numero Celular', max_length=50, null=True, verbose_name='Numero Celular')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrato.Cliente')),
            ],
            options={
                'verbose_name_plural': 'Referencia Celulares',
                'ordering': ['creacion'],
            },
        ),
        migrations.AddField(
            model_name='cuenta',
            name='moneda',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contrato.Moneda'),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('tipopago', models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Credito'), ('Plazos', 'Plazos')], help_text='Ingrese Tipo Pago', max_length=20, verbose_name='Pago')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contrato.Cliente')),
                ('lotes', models.ManyToManyField(blank=True, to='terreno.Lote')),
            ],
            options={
                'verbose_name_plural': 'Contratos',
                'ordering': ['creacion'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrato.Grupo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrato.Persona'),
        ),
    ]
