# Generated by Django 2.2.5 on 2019-09-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('actividad', models.CharField(blank=True, help_text='Ingrese del Nombre Actividad', max_length=50, null=True, verbose_name='Nombre Actividad')),
                ('copropietaria', models.ForeignKey(blank=True, help_text='Ingrese Propietaria', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietaria_copropietaria', to='contrato.Propietaria', verbose_name='Propietaria')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrato.Persona')),
            ],
            options={
                'verbose_name_plural': 'Propietaria',
                'ordering': ['creacion'],
            },
        ),
        migrations.CreateModel(
            name='Notaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('numeronotario', models.CharField(help_text='Ingrese Numero de Notaria', max_length=60, unique=True, verbose_name='Numero de Notaria')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrato.Persona')),
            ],
            options={
                'verbose_name_plural': 'Notaria de Fe Publica',
                'ordering': ['creacion'],
            },
        ),
        migrations.AddField(
            model_name='urbanizacion',
            name='propietaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrato.Propietaria'),
        ),
    ]
