# Generated by Django 2.2.5 on 2019-09-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_auto_20190924_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietaria',
            name='copropietaria',
        ),
        migrations.AlterField(
            model_name='persona',
            name='expedidopersona',
            field=models.CharField(blank=True, choices=[('', 'Desconocido'), ('Pando', 'Pando'), ('Beni', 'Beni'), ('La Paz', 'La Paz'), ('Cochabamba', 'Cochabamba'), ('Oruro', 'Oruro'), ('Santa Cruz', 'Santa Cruz'), ('Potosi', 'Potosi'), ('Tarija', 'Tarija'), ('Chuquisaca', 'Chuquisaca')], help_text='Ingrese Expedido Ci', max_length=20, verbose_name='Expedido'),
        ),
    ]
