# Generated by Django 2.2.5 on 2019-09-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_auto_20190924_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='urbanizacion',
            name='numeromatricula',
            field=models.CharField(blank=True, help_text='Ingrese Numero Matricula de Urbanizacion', max_length=50, null=True, verbose_name='Numero Matricula'),
        ),
        migrations.AlterField(
            model_name='urbanizacion',
            name='nombreubanizacion',
            field=models.CharField(blank=True, help_text='Ingrese del Nombre Urbanizacion', max_length=50, null=True, verbose_name='Nombre Urbanizacion'),
        ),
    ]
