# Generated by Django 2.2.5 on 2020-01-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0004_auto_20190924_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietaria',
            name='tipo',
            field=models.CharField(blank=True, choices=[('P', 'Primario'), ('R', 'Respresentante'), ('D', 'Delegado')], help_text='Propietario', max_length=20, verbose_name='Tipo Propietario'),
        ),
    ]
