# Generated by Django 2.2.5 on 2019-09-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('numerodistrito', models.IntegerField(blank=True, help_text='Ingrese el Numero del Distrito', null=True, verbose_name='Numero del Distrito')),
                ('nombredistrito', models.CharField(blank=True, help_text='Ingrese del Nombre Distrito', max_length=50, null=True, verbose_name='Nombre Distrito')),
                ('sigladistrito', models.CharField(blank=True, help_text='Ingrese la Sigla del Distrito', max_length=10, null=True, verbose_name='Sigla del Distrito')),
            ],
            options={
                'verbose_name_plural': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('largomedida', models.IntegerField(blank=True, null=True, verbose_name='Medida Largo del Lote')),
                ('anchomedida', models.IntegerField(blank=True, null=True, verbose_name='Medida Ancho del Lote')),
                ('superficietotal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Medidas',
                'ordering': ['creacion'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('latitudubicacion', models.CharField(blank=True, help_text='Ingrese la Latitud', max_length=30, null=True, verbose_name='Latitud')),
                ('longitudubicacion', models.CharField(blank=True, help_text='Ingrese la Longitud', max_length=30, null=True, verbose_name='Longitud')),
                ('descripcionubicacion', models.CharField(blank=True, help_text='Ingrese Descripcion de la Ubicacion', max_length=50, null=True, verbose_name='Descripcion de la Ubicacion')),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Manzano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('codigomanzano', models.CharField(help_text='Ingresa Codigo Manzano', max_length=80, null=True, verbose_name='Codigo Manzano')),
                ('numeromanzano', models.IntegerField(blank=True, help_text='Ingrese el Numero del Manzano', null=True, verbose_name='Numero del Manzano')),
                ('siglamanzano', models.CharField(blank=True, default='', help_text='Ingrese la Sigla del Manzano', max_length=10, null=True, verbose_name='Sigla del Manzano')),
                ('procesomanzano', models.CharField(choices=[('L', 'Libre'), ('R', 'Reservado'), ('C', 'Compra'), ('V', 'Vendido')], help_text='Ingrese Proceso Manzano', max_length=20, verbose_name='Proceso')),
                ('distritos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='terreno.Distrito')),
            ],
            options={
                'verbose_name_plural': 'Manzanos',
                'ordering': ['creacion'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('codigolote', models.CharField(help_text='Ingresa Codigo Lote', max_length=80, null=True, verbose_name='Codigo Lote')),
                ('numerolote', models.IntegerField(blank=True, help_text='Ingrese el Numero del Lote', null=True, verbose_name='Numero del Lote')),
                ('siglalote', models.CharField(blank=True, default='', help_text='Ingrese la Sigla del Lote', max_length=10, null=True, verbose_name='Sigla del Lote')),
                ('procesolote', models.CharField(choices=[('L', 'Libre'), ('R', 'Reservado'), ('C', 'Compra'), ('V', 'Vendido')], help_text='Ingrese Proceso Lote', max_length=20, verbose_name='Proceso')),
                ('Medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terreno.Medida')),
                ('manzanos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terreno.Manzano')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terreno.Ubicacion')),
            ],
            options={
                'verbose_name_plural': 'Lotes',
                'ordering': ['creacion'],
            },
        ),
    ]
